# Intro to numpy library

In a `markdown` cell we can use Markdown formatting. [Here is a cheatsheet.](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

My list:
- first **element**
- second *element*

## How Jupter Notebook works?

In [11]:
first_name = 'Piotr'
last_name = 'GG'
import time
time.sleep(3)

In [12]:
print(first_name, last_name)

Piotr GG


To see the results of expressions or variables, etc. we don't have to use `print`. Last line of the code cell will be displayed in the output part of the cell.

In [13]:
10 * 5

50

In [14]:
shoe_number = 46
shoe_number

46

In [15]:
my_dict = {
    'first_name': 'Piotr',
    'last_name': 'GG',
}
my_dict

{'first_name': 'Piotr', 'last_name': 'GG'}

## NumPy

[Documentation](https://numpy.org/doc/1.24/index.html)

NumPy, by default in Python installation is not available. But if we are using Anaconda, then NumPy, Pandas and other libraries are installed and we don't have to worry about them.

When using Anaconda and Jupter Notebooks we are using different virtual environment (venv) than when using PyCharm.

In [16]:
import numpy as np

In [17]:
np.__version__

'1.20.3'

`ndarray` - n-dimensional array

In [18]:
arr = np.array([10, 20, 30])  # based on the list [10, 20, 30] I'm creating NumPy array.
arr, type(arr)

(array([10, 20, 30]), numpy.ndarray)

In [19]:
arr[2]

30

In [20]:
arr.dtype

dtype('int64')

We can store only one data type in NumPy array. For example, we can't store at the same time number and string.

[Data types available in NumPy](https://numpy.org/doc/stable/user/basics.types.html)

Extract from available data types:

Number in the type name refers to the number of bits (1 byte = 8 bits).

- **`int8`** - like `byte` in Java or `signed char` in C, range od -128 do +127
- **`int16`** - like `short`, range from -32_768 to +32_767
- **`int32`** - like `int`, range from -2_147_483_648 to +2_147_483_647
- **`int64`** - like `long`, range to 9223372036854775807 (19 cyfr)
- **`float16`** - floating point numbers with low precision, about 4-5 digits
- **`float32`** - like `float` in C or Java; medium precision, about 7-8 digits
- **`float64`** - like `double` in C or Java, or standard `float` in Python; big precision, about 14-15 digits

In [21]:
a = np.int32(5)
b = np.int32(1_000_000_000)
a, b

(5, 1000000000)

In [22]:
a * b  # 705_032_704, this problem is called integer overflow

/var/folders/__/0gvd5dsj22b9cbv4hzvln3pw0000gn/T/ipykernel_31677/1354736782.py:1: RuntimeWarning: overflow encountered in int_scalars
  a * b  # 705_032_704, this problem is called integer overflow


705032704

In [23]:
c = np.int32(2_147_483_647)
c, c + np.int32(1) # this problem is called integer overflow

/var/folders/__/0gvd5dsj22b9cbv4hzvln3pw0000gn/T/ipykernel_31677/3225359074.py:2: RuntimeWarning: overflow encountered in int_scalars
  c, c + np.int32(1) # this problem is called integer overflow


(2147483647, -2147483648)

Integer overflow can be problematic...
[Ariane 5](https://youtu.be/PK_yguLapgA?t=76)
- https://hownot2code.wordpress.com/2016/09/02/a-space-error-370-million-for-an-integer-overflow/
- https://www.bbc.com/future/article/20150505-the-numbers-that-lead-to-disaster


## Basics of NumPy arrays

In [24]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
a, b

(array([1, 2, 3, 4, 5]), array([10, 20, 30, 40, 50]))

In [25]:
# we can use indexing operator
b[3]

40

In [26]:
for number in a:
    print(number)

1
2
3
4
5


In [27]:
# [1, 2, 3] * [4, 5, 6] - is that possible in standard Python? To multiply two lists?
# [1, 2, 3] * [4, 5, 6] KO: TypeError: can't multiply sequence by non-int of type 'list'

In [28]:
a, b

(array([1, 2, 3, 4, 5]), array([10, 20, 30, 40, 50]))

In [29]:
a + b, a - b, a * b, a / b

(array([11, 22, 33, 44, 55]),
 array([ -9, -18, -27, -36, -45]),
 array([ 10,  40,  90, 160, 250]),
 array([0.1, 0.1, 0.1, 0.1, 0.1]))

## Getting information about NumPy arrays

In [30]:
# https://en.wikipedia.org/wiki/Matrix_(mathematics)
m = np.array([
    [10, 11, 12, 13, 14],
    [20, 21, 22, 23, 24],
    [30, 31, 32, 33, 34],
])
m

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [31]:
m.size  # how many elements in array?

15

In [32]:
len(m)  # in this case how many rows?

3

In [33]:
m.ndim  # how many dimensions I have?

2

In [34]:
m.shape

(3, 5)

## Ways of creating NumPy arrays

In [35]:
# as earlier we can create arrays based on iterables like lists or tuples, etc.
a = np.array([1, 2, 3, 4, 5])
a, a.dtype

(array([1, 2, 3, 4, 5]), dtype('int64'))

In [36]:
a = np.array([1, 2, 3, 4, 5], dtype='float16')
a, a.dtype

(array([1., 2., 3., 4., 5.], dtype=float16), dtype('float16'))

In [37]:
np.full(5, 10)  # np.full(shape, value)

array([10, 10, 10, 10, 10])

In [38]:
np.full((3, 5), 15)

array([[15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15]])

In [39]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
np.diag([1, 2, 3, 4, 5])  # diagonal matrix

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [42]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [43]:
np.arange(10)  # it's similar to pythons range function...

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.arange(-10, 11)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10])

In [45]:
np.arange(-10, 11, 2)

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8,  10])

In [46]:
np.arange(1.0, 2.1, 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

### reshape

In [47]:
arr = np.arange(24)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [48]:
arr.reshape(4, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [49]:
arr.reshape(6, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [50]:
arr.reshape(4, -1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

## Operations

In [51]:
a = np.arange(40).reshape(5, 8)
b = np.arange(50, 90).reshape(5, 8)
a, b

(array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39]]),
 array([[50, 51, 52, 53, 54, 55, 56, 57],
        [58, 59, 60, 61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70, 71, 72, 73],
        [74, 75, 76, 77, 78, 79, 80, 81],
        [82, 83, 84, 85, 86, 87, 88, 89]]))

In [52]:
a + b

array([[ 50,  52,  54,  56,  58,  60,  62,  64],
       [ 66,  68,  70,  72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90,  92,  94,  96],
       [ 98, 100, 102, 104, 106, 108, 110, 112],
       [114, 116, 118, 120, 122, 124, 126, 128]])

In [53]:
a - b, a * b, a / b

(array([[-50, -50, -50, -50, -50, -50, -50, -50],
        [-50, -50, -50, -50, -50, -50, -50, -50],
        [-50, -50, -50, -50, -50, -50, -50, -50],
        [-50, -50, -50, -50, -50, -50, -50, -50],
        [-50, -50, -50, -50, -50, -50, -50, -50]]),
 array([[   0,   51,  104,  159,  216,  275,  336,  399],
        [ 464,  531,  600,  671,  744,  819,  896,  975],
        [1056, 1139, 1224, 1311, 1400, 1491, 1584, 1679],
        [1776, 1875, 1976, 2079, 2184, 2291, 2400, 2511],
        [2624, 2739, 2856, 2975, 3096, 3219, 3344, 3471]]),
 array([[0.        , 0.01960784, 0.03846154, 0.05660377, 0.07407407,
         0.09090909, 0.10714286, 0.12280702],
        [0.13793103, 0.15254237, 0.16666667, 0.18032787, 0.19354839,
         0.20634921, 0.21875   , 0.23076923],
        [0.24242424, 0.25373134, 0.26470588, 0.27536232, 0.28571429,
         0.29577465, 0.30555556, 0.31506849],
        [0.32432432, 0.33333333, 0.34210526, 0.35064935, 0.35897436,
         0.36708861, 0.375     , 0.3827160

[Dot product](https://en.wikipedia.org/wiki/Dot_product)
![Matrix multiplication](https://miro.medium.com/max/1400/1*YGcMQSr0ge_DGn96WnEkZw.png)

In [54]:
a = np.arange(40).reshape(5, 8)
b = np.arange(50, 90).reshape(8, 5)
a.dot(b), a @ b

(array([[ 2100,  2128,  2156,  2184,  2212],
        [ 6420,  6512,  6604,  6696,  6788],
        [10740, 10896, 11052, 11208, 11364],
        [15060, 15280, 15500, 15720, 15940],
        [19380, 19664, 19948, 20232, 20516]]),
 array([[ 2100,  2128,  2156,  2184,  2212],
        [ 6420,  6512,  6604,  6696,  6788],
        [10740, 10896, 11052, 11208, 11364],
        [15060, 15280, 15500, 15720, 15940],
        [19380, 19664, 19948, 20232, 20516]]))

In [55]:
a, a + 100

(array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39]]),
 array([[100, 101, 102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113, 114, 115],
        [116, 117, 118, 119, 120, 121, 122, 123],
        [124, 125, 126, 127, 128, 129, 130, 131],
        [132, 133, 134, 135, 136, 137, 138, 139]]))

## Broadcasting

In [56]:
a = np.arange(3).reshape((3, 1))
a

array([[0],
       [1],
       [2]])

In [57]:
b = np.arange(3)
b

array([0, 1, 2])

In [58]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

## Idexing operator usage with NumPy arrays

In [59]:
a = np.arange(10, 20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [60]:
a[1], a[0:3], a[0:6:2]

(11, array([10, 11, 12]), array([10, 12, 14]))

In [61]:
a = np.arange(50).reshape(5, 10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [62]:
# indexing operator support also multidimensional NumPy arrays
a[1, 3]

13

In [63]:
# for each dimension we can use all features like start, stop and step...
a[2:4, 4:7]

array([[24, 25, 26],
       [34, 35, 36]])

In [64]:
a[-3:-1, -6:-3]

array([[24, 25, 26],
       [34, 35, 36]])

In [65]:
a[-3:-1, -6:-3] = 1
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23,  1,  1,  1, 27, 28, 29],
       [30, 31, 32, 33,  1,  1,  1, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [66]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23,  1,  1,  1, 27, 28, 29],
       [30, 31, 32, 33,  1,  1,  1, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [71]:
a[1:3, :]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23,  1,  1,  1, 27, 28, 29]])

In [72]:
a[:, 1:3]

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32],
       [41, 42]])

In [73]:
arr = np.arange(60).reshape(3, 4, 5)
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [74]:
arr[1, 0, 3]

23

In [75]:
arr[1, :, :]

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [76]:
# instead of using two empty ranges (arr[1, :, :]) we can use ellipsis operator
arr[1, ...]

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [79]:
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [80]:
arr[..., 3]

array([[ 3,  8, 13, 18],
       [23, 28, 33, 38],
       [43, 48, 53, 58]])

## Iterating through NumPy array

In [84]:
for matrix in arr:
    for row in matrix:
        for column_value in row:
            print(column_value)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59


## How we can test how much time certain cell needs to be executed?

In [86]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%

In [91]:
%%timeit -r 10 -n 100
# r - how many repeats of the cell we should do, how many timings, one repeat is one measurement and we execute the code n times within one measurement
# n - how many times we will run the code within one repeat or one measurement
# https://simple.wikipedia.org/wiki/Orders_of_magnitude_(time)
result = []
for number in range(1, 10_001):
    result.append(number ** 2)

2.82 ms ± 134 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [92]:
result = []
for number in range(1, 10_001):
    result.append(number ** 2)
result

[1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801,
 10000,
 10201,
 10404,
 10609,
 10816,
 11025,
 11236,
 11449,
 11664,
 11881,
 12100,
 12321,
 12544,
 12769,
 12996,
 13225,
 13456,
 13689,
 13924,
 14161,
 14400,
 14641,
 14884,
 15129,
 15376,
 15625,
 15876,
 16129,
 16384,
 16641,
 16900,
 17161,
 17424,
 17689,
 17956,
 18225,
 18496,
 18769,
 19044,
 19321,
 19600,
 19881,
 20164,
 20449

In [93]:
[number ** 2 for number in range(1, 10_001)]

[1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801,
 10000,
 10201,
 10404,
 10609,
 10816,
 11025,
 11236,
 11449,
 11664,
 11881,
 12100,
 12321,
 12544,
 12769,
 12996,
 13225,
 13456,
 13689,
 13924,
 14161,
 14400,
 14641,
 14884,
 15129,
 15376,
 15625,
 15876,
 16129,
 16384,
 16641,
 16900,
 17161,
 17424,
 17689,
 17956,
 18225,
 18496,
 18769,
 19044,
 19321,
 19600,
 19881,
 20164,
 20449

In [94]:
%%timeit -r 10 -n 100
[number ** 2 for number in range(1, 10_001)]

2.63 ms ± 73 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [96]:
%%timeit -r 10 -n 100
np.arange(1, 10_001) ** 2

The slowest run took 4.44 times longer than the fastest. This could mean that an intermediate result is being cached.
20.7 µs ± 13.3 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [95]:
np.arange(1, 10_001) ** 2

array([        1,         4,         9, ...,  99960004,  99980001,
       100000000])

2.82 ms vs 2.63 ms vs 20 microseconds

In [97]:
2.82E-3 / 20E-6

141.0