# Intro to numpy library

In a `markdown` cell we can use Markdown formatting. [Here is a cheatsheet.](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

My list:
- first **element**
- second *element*

## How Jupter Notebook works?

In [22]:
first_name = 'Piotr'
last_name = 'GG'
import time
time.sleep(3)

In [23]:
print(first_name, last_name)

Piotr GG


To see the results of expressions or variables, etc. we don't have to use `print`. Last line of the code cell will be displayed in the output part of the cell.

In [24]:
10 * 5

50

In [25]:
shoe_number = 46
shoe_number

46

In [26]:
my_dict = {
    'first_name': 'Piotr',
    'last_name': 'GG',
}
my_dict

{'first_name': 'Piotr', 'last_name': 'GG'}

## NumPy

[Documentation](https://numpy.org/doc/1.24/index.html)

NumPy, by default in Python installation is not available. But if we are using Anaconda, then NumPy, Pandas and other libraries are installed and we don't have to worry about them.

When using Anaconda and Jupter Notebooks we are using different virtual environment (venv) than when using PyCharm.

In [27]:
import numpy as np

In [28]:
np.__version__

'1.20.3'

`ndarray` - n-dimensional array

In [29]:
arr = np.array([10, 20, 30])  # based on the list [10, 20, 30] I'm creating NumPy array.
arr, type(arr)

(array([10, 20, 30]), numpy.ndarray)

In [30]:
arr[2]

30

In [31]:
arr.dtype

dtype('int64')

We can store only one data type in NumPy array. For example, we can't store at the same time number and string.

[Data types available in NumPy](https://numpy.org/doc/stable/user/basics.types.html)

Extract from available data types:

Number in the type name refers to the number of bits (1 byte = 8 bits).

- **`int8`** - like `byte` in Java or `signed char` in C, range od -128 do +127
- **`int16`** - like `short`, range from -32_768 to +32_767
- **`int32`** - like `int`, range from -2_147_483_648 to +2_147_483_647
- **`int64`** - like `long`, range to 9223372036854775807 (19 cyfr)
- **`float16`** - floating point numbers with low precision, about 4-5 digits
- **`float32`** - like `float` in C or Java; medium precision, about 7-8 digits
- **`float64`** - like `double` in C or Java, or standard `float` in Python; big precision, about 14-15 digits

In [32]:
a = np.int32(5)
b = np.int32(1_000_000_000)
a, b

(5, 1000000000)

In [33]:
a * b  # 705_032_704, this problem is called integer overflow

/var/folders/__/0gvd5dsj22b9cbv4hzvln3pw0000gn/T/ipykernel_58776/1354736782.py:1: RuntimeWarning: overflow encountered in int_scalars
  a * b  # 705_032_704, this problem is called integer overflow


705032704

In [34]:
c = np.int32(2_147_483_647)
c, c + np.int32(1) # this problem is called integer overflow

/var/folders/__/0gvd5dsj22b9cbv4hzvln3pw0000gn/T/ipykernel_58776/3225359074.py:2: RuntimeWarning: overflow encountered in int_scalars
  c, c + np.int32(1) # this problem is called integer overflow


(2147483647, -2147483648)

Integer overflow can be problematic...
[Ariane 5](https://youtu.be/PK_yguLapgA?t=76)
- https://hownot2code.wordpress.com/2016/09/02/a-space-error-370-million-for-an-integer-overflow/
- https://www.bbc.com/future/article/20150505-the-numbers-that-lead-to-disaster


## Basics of NumPy arrays

In [35]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
a, b

(array([1, 2, 3, 4, 5]), array([10, 20, 30, 40, 50]))

In [36]:
# we can use indexing operator
b[3]

40

In [37]:
for number in a:
    print(number)

1
2
3
4
5


In [38]:
# [1, 2, 3] * [4, 5, 6] - is that possible in standard Python? To multiply two lists?
# [1, 2, 3] * [4, 5, 6] KO: TypeError: can't multiply sequence by non-int of type 'list'

In [39]:
a, b

(array([1, 2, 3, 4, 5]), array([10, 20, 30, 40, 50]))

In [40]:
a + b, a - b, a * b, a / b

(array([11, 22, 33, 44, 55]),
 array([ -9, -18, -27, -36, -45]),
 array([ 10,  40,  90, 160, 250]),
 array([0.1, 0.1, 0.1, 0.1, 0.1]))

## Getting information about NumPy arrays

In [41]:
# https://en.wikipedia.org/wiki/Matrix_(mathematics)
m = np.array([
    [10, 11, 12, 13, 14],
    [20, 21, 22, 23, 24],
    [30, 31, 32, 33, 34],
])
m

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [42]:
m.size  # how many elements in array?

15

In [43]:
len(m)  # in this case how many rows?

3

In [44]:
m.ndim  # how many dimensions I have?

2

In [45]:
m.shape

(3, 5)

## Ways of creating NumPy arrays

In [46]:
# as earlier we can create arrays based on iterables like lists or tuples, etc.
a = np.array([1, 2, 3, 4, 5])
a, a.dtype

(array([1, 2, 3, 4, 5]), dtype('int64'))

In [47]:
a = np.array([1, 2, 3, 4, 5], dtype='float16')
a, a.dtype

(array([1., 2., 3., 4., 5.], dtype=float16), dtype('float16'))

In [48]:
np.full(5, 10)  # np.full(shape, value)

array([10, 10, 10, 10, 10])

In [49]:
np.full((3, 5), 15)

array([[15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15]])

In [50]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [52]:
np.diag([1, 2, 3, 4, 5])  # diagonal matrix

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [53]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [54]:
np.arange(10)  # it's similar to pythons range function...

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
np.arange(-10, 11)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10])

In [56]:
np.arange(-10, 11, 2)

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8,  10])

In [57]:
np.arange(1.0, 2.1, 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

### reshape

In [58]:
arr = np.arange(24)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [59]:
arr.reshape(4, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [60]:
arr.reshape(6, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [61]:
arr.reshape(4, -1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

## Operations

In [62]:
a = np.arange(40).reshape(5, 8)
b = np.arange(50, 90).reshape(5, 8)
a, b

(array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39]]),
 array([[50, 51, 52, 53, 54, 55, 56, 57],
        [58, 59, 60, 61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70, 71, 72, 73],
        [74, 75, 76, 77, 78, 79, 80, 81],
        [82, 83, 84, 85, 86, 87, 88, 89]]))

In [63]:
a + b

array([[ 50,  52,  54,  56,  58,  60,  62,  64],
       [ 66,  68,  70,  72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90,  92,  94,  96],
       [ 98, 100, 102, 104, 106, 108, 110, 112],
       [114, 116, 118, 120, 122, 124, 126, 128]])

In [64]:
a - b, a * b, a / b

(array([[-50, -50, -50, -50, -50, -50, -50, -50],
        [-50, -50, -50, -50, -50, -50, -50, -50],
        [-50, -50, -50, -50, -50, -50, -50, -50],
        [-50, -50, -50, -50, -50, -50, -50, -50],
        [-50, -50, -50, -50, -50, -50, -50, -50]]),
 array([[   0,   51,  104,  159,  216,  275,  336,  399],
        [ 464,  531,  600,  671,  744,  819,  896,  975],
        [1056, 1139, 1224, 1311, 1400, 1491, 1584, 1679],
        [1776, 1875, 1976, 2079, 2184, 2291, 2400, 2511],
        [2624, 2739, 2856, 2975, 3096, 3219, 3344, 3471]]),
 array([[0.        , 0.01960784, 0.03846154, 0.05660377, 0.07407407,
         0.09090909, 0.10714286, 0.12280702],
        [0.13793103, 0.15254237, 0.16666667, 0.18032787, 0.19354839,
         0.20634921, 0.21875   , 0.23076923],
        [0.24242424, 0.25373134, 0.26470588, 0.27536232, 0.28571429,
         0.29577465, 0.30555556, 0.31506849],
        [0.32432432, 0.33333333, 0.34210526, 0.35064935, 0.35897436,
         0.36708861, 0.375     , 0.3827160

[Dot product](https://en.wikipedia.org/wiki/Dot_product)
![Matrix multiplication](https://miro.medium.com/max/1400/1*YGcMQSr0ge_DGn96WnEkZw.png)

In [65]:
a = np.arange(40).reshape(5, 8)
b = np.arange(50, 90).reshape(8, 5)
a.dot(b), a @ b

(array([[ 2100,  2128,  2156,  2184,  2212],
        [ 6420,  6512,  6604,  6696,  6788],
        [10740, 10896, 11052, 11208, 11364],
        [15060, 15280, 15500, 15720, 15940],
        [19380, 19664, 19948, 20232, 20516]]),
 array([[ 2100,  2128,  2156,  2184,  2212],
        [ 6420,  6512,  6604,  6696,  6788],
        [10740, 10896, 11052, 11208, 11364],
        [15060, 15280, 15500, 15720, 15940],
        [19380, 19664, 19948, 20232, 20516]]))

In [66]:
a, a + 100

(array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39]]),
 array([[100, 101, 102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113, 114, 115],
        [116, 117, 118, 119, 120, 121, 122, 123],
        [124, 125, 126, 127, 128, 129, 130, 131],
        [132, 133, 134, 135, 136, 137, 138, 139]]))

## Broadcasting

In [67]:
a = np.arange(3).reshape((3, 1))
a

array([[0],
       [1],
       [2]])

In [68]:
b = np.arange(3)
b

array([0, 1, 2])

In [69]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

## Idexing operator usage with NumPy arrays

In [70]:
a = np.arange(10, 20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [71]:
a[1], a[0:3], a[0:6:2]

(11, array([10, 11, 12]), array([10, 12, 14]))

In [72]:
a = np.arange(50).reshape(5, 10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [73]:
# indexing operator support also multidimensional NumPy arrays
a[1, 3]

13

In [74]:
# for each dimension we can use all features like start, stop and step...
a[2:4, 4:7]

array([[24, 25, 26],
       [34, 35, 36]])

In [75]:
a[-3:-1, -6:-3]

array([[24, 25, 26],
       [34, 35, 36]])

In [76]:
a[-3:-1, -6:-3] = 1
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23,  1,  1,  1, 27, 28, 29],
       [30, 31, 32, 33,  1,  1,  1, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])